version: '3.8'
services:
  api:
    container_name: nest-api
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/escuela
    depends_on:
      - mongodb
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 